meta:
  title: NHentaiStatistics Core
  author: bodand
  description: NHentaiStatistics' core, speaks with nhentai, gets doujin data. Supplies easy-to-use classes to do so.
  branding:
    icon: doc/stc/img/icon.png
    logo: doc/stc/img/logo.png

build:
  dir: build/cutedocs

theme:
  colors:
    primary: CB602D
    secondary: A2A2A2
    text: A9B7C6
    nav: 1E2021
    background: 3C3F41


articles:
  Introduction:
    Intro: doc/src/itr/intro.md
    History: doc/src/itr/history.md
  Installing:
    Maven: doc/src/ins/mvn.md
    Gradle: doc/src/ins/gradle.md
    Sbt: doc/src/ins/sbt.md
    Local: doc/src/ins/local.md
  Usage:
    ScalaDoc: doc/src/use/scaladoc.md
    Gallery class: doc/src/use/galleryclass.md
    HentaiData trait: doc/src/use/hentaidata.md
    Getting a doujin: doc/src/use/onedoujin.md
